#!/usr/bin/env bash
set -euo pipefail

# resolve repo root from this script location
repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_dir"

# ensure binary exists
if [[ ! -x "$repo_dir/pin" ]]; then
  go build -o pin .
fi

out_file="$repo_dir/docs/help-docs-build-generated.md"

python3 - "$out_file" <<'PY'
import subprocess
import sys

out_file = sys.argv[1]
help_text = subprocess.check_output(["./pin", "--help"], text=True)
lines = [ln.rstrip("\n") for ln in help_text.splitlines()]

def find_idx(label):
    for i, ln in enumerate(lines):
        if ln.strip() == label:
            return i
    return -1

usage_i = find_idx("Usage:")
aliases_i = find_idx("Aliases:")
cmds_i = find_idx("Available Commands:")
flags_i = find_idx("Flags:")
more_i = -1
for i, ln in enumerate(lines):
    if ln.startswith('Use "pin '):
        more_i = i
        break

desc_lines = lines[:usage_i if usage_i != -1 else len(lines)]
tail_lines = lines[usage_i:] if usage_i != -1 else []

out = []
out.append("<!--")
out.append("This file is auto-generated by scripts/gen_help_docs.sh.")
out.append("Do not edit by hand. Run scripts/gen_help_docs.sh to update.")
out.append("-->")
out.append("")
out.append("# pin help")
out.append("")

def flush_paragraph(buf):
    if not buf:
        return
    out.append(" ".join(buf).strip())
    out.append("")
    buf.clear()

# Format the long description into markdown
para = []
i = 0
while i < len(desc_lines):
    ln = desc_lines[i]
    if ln.strip() == "":
        flush_paragraph(para)
        i += 1
        continue

    # Detect heading lines that introduce indented blocks
    if ln.endswith(":") and i + 1 < len(desc_lines) and desc_lines[i + 1].startswith("  "):
        flush_paragraph(para)
        heading = ln[:-1].strip()
        out.append(f"## {heading}")
        out.append("")
        block = []
        i += 1
        while i < len(desc_lines) and desc_lines[i].startswith("  "):
            block.append(desc_lines[i][2:])
            i += 1
        out.append("```bash")
        out.extend(block)
        out.append("```")
        out.append("")
        continue

    # Regular line -> paragraph
    para.append(ln.strip())
    i += 1

flush_paragraph(para)

def collect_indented(start_idx):
    block = []
    i = start_idx + 1
    while i < len(lines) and lines[i].startswith("  "):
        block.append(lines[i][2:])
        i += 1
    return block

if usage_i != -1:
    out.append("## Usage")
    out.append("")
    block = collect_indented(usage_i)
    if block:
        out.append("```bash")
        out.extend(block)
        out.append("```")
        out.append("")

if aliases_i != -1:
    out.append("## Aliases")
    out.append("")
    block = collect_indented(aliases_i)
    if block:
        out.append(", ".join(block))
        out.append("")

if cmds_i != -1:
    out.append("## Commands")
    out.append("")
    out.append("| Command | Description |")
    out.append("| --- | --- |")
    block = collect_indented(cmds_i)
    for ln in block:
        parts = ln.strip().split(None, 1)
        if not parts:
            continue
        cmd = parts[0]
        desc = parts[1] if len(parts) > 1 else ""
        out.append(f"| `{cmd}` | {desc} |")
    out.append("")

if flags_i != -1:
    out.append("## Flags")
    out.append("")
    block = collect_indented(flags_i)
    for ln in block:
        out.append(f"- `{ln.strip()}`")
    out.append("")

if more_i != -1:
    out.append(lines[more_i].strip())
    out.append("")

with open(out_file, "w", encoding="utf-8") as f:
    f.write("\n".join(out).rstrip() + "\n")
PY

echo "Wrote $out_file"
